forward port to node-cpp-skel

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,56 +1,137 @@
-language: cpp
+language: node_js
 
 sudo: false
 
+# enable c++11/14 builds
 addons:
   apt:
-    sources:
-      - ubuntu-toolchain-r-test
-      - llvm-toolchain-precise-3.5
-    packages:
-      - clang-3.5
-
-matrix:
-  include:
-     # Linux
-     - os: linux
-       compiler: clang
-       env: NODE_VERSION="4.4.2" PUBLISHABLE=true
-     - os: linux
-       compiler: clang
-       env: NODE_VERSION="6.11.2" PUBLISHABLE=true
-     # Debug build (only for testing)
-     - os: linux
-       compiler: clang
-       env: NODE_VERSION="4.4.2" NPM_FLAGS="--debug"
-     # OS X
-     - os: osx
-       compiler: clang
-       env: NODE_VERSION="4.4.2" PUBLISHABLE=true
-     - os: osx
-       compiler: clang
-       env: NODE_VERSION="6.11.2" PUBLISHABLE=true
-
-env:
-  global:
-    - secure: "RMUZUUP2xBRULwEZ5ykYIzo9drjjzuV1p1Pnrw06+bDzCgfL9djgrex1lWg5pNP5BR1JlTxsnniroSZg6WSkShXQwIZ3407ddhXhRoxumc/uD7gzdv1ogW8OgIZfUX1WOW239cOHBUuLLWZyN4Fhsu19HnLx9gKajZTlnrGGkhUvkKbROp9SCKa2hVhNP1y7zsuGM+zQMOPVKcg0lWj9Bs6UAOafzahNc6UQVw7S7+7bp5CWRw8mpvhAMduYwQQCNnZiU1rkxQKJ7TyXgeYRbS5EgkZpw476inhUKFXl6v4XYqSyIoJ6oPCy/1qpzM/W6EtcMNJboris3/No56ERj6afJvlcVs95R/aRqAe/PSyyK+sPmKicBFkWfWPyU+y+FmRQ5JBpIaFw/uL6KLVYCA4riC666+j/4XsN/YGfxwyUPB3FtT7i57u9ivj9QLtoJDYGaQIQwXVuG9LnkGuGutNKT5p+oX+QDFW82jmpwcXqZ03sH9Ty4P+UsV15K97b6Q+rNeMbIpharlv+uYQLetOCN4FlEWAM/Bxl+IdwL38pUD/50i4enGof9tJeNIh5sV35pG7w7AG5jnY3rwROI1hXVlVtNsi+saQ5IR1oty23GuZNb+wzy5bp84FA9BJg4Sgsoacu2jhP5VLtM0AYdy8SCKbjTZrosMmgloOnXdY="
-    - secure: "yq6M4D8J4lUBb/SHa/4qO+dn9cXVuUoUo+UWgvsypBiwSi1+89YADO8QK9UMQgF+uqOxoWSd9S4QrV14VBWmxLCHjT71OuyIv3ZqTMvWAFLR5e2RYsydPdS9RXVe/XTKkBUffsQXmG4tFXOwz/mdMxarjcPwerOgeFb5RFeKOCguJ607dtlAnDSTtS3Z6sPIu48kknDmVTpbNKZMHgyUg4Y7SrJ8zRK4tYbjeXo6XvqK5HZ7SW117pNKx33NxcbeudgHcWrIrAaquXEA/Ep/7ILC6Q4khblSNz7I7Z14Tw8R4peT6aQ5CKx/PRYyEp1vnaJjx2eVQIUq9JRlARE1Pk0B2YUF2kSYf4kQcj/3swtniIkUKKdZCqmZzc/ZrcYGfLoqJn2XhuDYjwvRgQBUvCZY42C4JLJ0jjfJVVkiFooTmADtpwDeWtMDBOwbM9uJJd7rbxQnYvCYQxIG4bYnJQBNvBCmeOgP4VFmmPxIP3pKnEivB03ZEXEpp4qBybrBxDsR3nQVcUqeaFyVtEq2B6NDTzK9F9JOX3Tve9J068F0epsiWWI2FoBJUPngY/E+uSoUkr0VISi9Oh+yZ6pZlE2PLsxKoB2fVnX6xuGbtS86tG6kFbBTbfEUiZbIIYpNQyoWLi9Fkt3pa1md+RxJvZSqqMNMZAlR4dLcMxrmWho="
-
-before_install:
-  - if [[ $(uname -s) == 'Linux' ]]; then
-      export CXX="clang++-3.5";
-      export CC="clang-3.5";
-    fi;
-  - rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
-  - source ~/.nvm/nvm.sh
-  - nvm install $NODE_VERSION
-  - nvm use $NODE_VERSION
+    sources: [ 'ubuntu-toolchain-r-test' ]
+    packages: [ 'libstdc++-4.9-dev' ]
 
 install:
-  - npm install --build-from-source --clang=1 ${NPM_FLAGS:-}
+  # set up the environment by installing mason and clang++
+  - ./scripts/setup.sh --config local.env
+  # put mason and clang++ on PATH
+  - source local.env
+  - node -v
+  - which node
+  - clang++ -v
+  - which clang++
+  - make ${BUILDTYPE}
 
-script:
+# *Here we run tests*
+# We prefer running tests in the 'before_script' section rather than 'script' to ensure fast failure.
+# Be aware that if you use the 'script' section it will continue running all commands in the section even if one line fails.
+# This is documented at https://docs.travis-ci.com/user/customizing-the-build#Breaking-the-Build
+# We don't want this behavior because otherwise we might risk publishing builds when the tests did not pass.
+# For this reason, we disable the 'script' section below, since we prefer using 'before_script'.
+before_script:
   - npm test
+  # after successful tests, publish binaries if specified in commit message
+  - ./scripts/publish.sh --toolset=${TOOLSET:-} --debug=$([ "${BUILDTYPE}" == 'debug' ] && echo "true" || echo "false")
 
-after_success:
-  - if [[ ${PUBLISHABLE:-} == true ]]; then ./test/travis-publish.sh; fi
+# We set 'script' here to an empty array to prevent this section from automatically running 'npm test'
+# The reason we do this is mentioned above in the comment about the 'before_script' stage.
+# For reference, the default travis behavior which we override comes from https://github.com/travis-ci/travis-build/blob/e5a45cbf49e0d9e27398e76e5f25dd7706feb6aa/lib/travis/build/script/node_js.rb#L62-L69.
+script: []
+
+# the matrix allows you to specify different operating systems and environments to 
+# run your tests and build binaries
+matrix:
+  include:
+    # linux publishable node v4/release
+    - os: linux
+      env: BUILDTYPE=release
+      node_js: 4
+    # linux publishable node v4/debug
+    - os: linux
+      env: BUILDTYPE=debug
+      node_js: 4
+    # linux publishable node v6
+    - os: linux
+      env: BUILDTYPE=release
+      node_js: 6
+    # linux publishable node v6/debug
+    - os: linux
+      env: BUILDTYPE=debug
+      node_js: 6
+    # osx publishable node v4
+    - os: osx
+      osx_image: xcode8.2
+      env: BUILDTYPE=release
+      node_js: 4
+    # osx publishable node v6
+    - os: osx
+      osx_image: xcode8.2
+      env: BUILDTYPE=release
+      node_js: 6
+    # Sanitizer build node v4/Debug
+    - os: linux
+      env: BUILDTYPE=debug TOOLSET=asan
+      node_js: 4
+      # Overrides `install` to set up custom asan flags
+      install:
+        - ./scripts/setup.sh --config local.env
+        # put mason and clang++ on PATH
+        - source local.env
+        # Note: to build without stopping on errors remove the -fno-sanitize-recover=all flag
+        # You might want to do this if there are multiple errors and you want to see them all before fixing
+        - export CXXFLAGS="${MASON_SANITIZE_CXXFLAGS} -fno-sanitize-recover=all"
+        - export LDFLAGS="${MASON_SANITIZE_LDFLAGS}"
+        - make ${BUILDTYPE}
+      # Overrides `script` to disable asan LD_PRELOAD before publishing
+      before_script:
+        - export LD_PRELOAD=${MASON_LLVM_RT_PRELOAD}
+        - export ASAN_OPTIONS=fast_unwind_on_malloc=0:${ASAN_OPTIONS}
+        - npm test
+        - unset LD_PRELOAD
+        # after successful tests, publish binaries if specified in commit message
+        - ./scripts/publish.sh --toolset=${TOOLSET:-} --debug=$([ "${BUILDTYPE}" == 'debug' ] && echo "true" || echo "false")
+    # g++ build (default builds all use clang++)
+    - os: linux
+      env: BUILDTYPE=debug CXX="g++-6" CC="gcc-6" CXXFLAGS="-Weffc++"
+      node_js: 4
+      addons:
+        apt:
+          sources:
+            - ubuntu-toolchain-r-test
+          packages:
+            - libstdc++-6-dev
+            - g++-6
+      # Overrides `install` to avoid initializing clang toolchain
+      install:
+        - make ${BUILDTYPE}
+      # Overrides `script` to disable publishing
+      before_script:
+        - npm test
+    # Coverage build
+    - os: linux
+      env: BUILDTYPE=debug CXXFLAGS="--coverage" LDFLAGS="--coverage"
+      node_js: 4
+      # Overrides `script` to publish coverage data to codecov
+      before_script:
+        - npm test
+        - mason install llvm-cov ${MASON_LLVM_RELEASE}
+        - mason link llvm-cov ${MASON_LLVM_RELEASE}
+        - which llvm-cov
+        - curl -S -f https://codecov.io/bash -o codecov
+        - chmod +x codecov
+        - ./codecov -x "llvm-cov gcov" -Z
+    # Clang format build
+    - os: linux
+      language: generic
+      env: BUILDTYPE=debug
+      node_js: 4
+      # Overrides `install` to avoid initializing clang toolchain
+      install:
+        # First run the clang-tidy target
+        # This target does not currently return non-zero when problems
+        # are fixed, but rather it fixes automatically. Changed files
+        # will be detected by the format target and will trigger an error
+        - make tidy
+        # Now we run the clang-format script. Any code formatting changes
+        # will trigger the build to fail (idea here is to get us to pay attention
+        # and get in the habit of running these locally before committing)
+        - make format
+      # Overrides `script`, no need to run tests
+      before_script:
